In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [28]:
data = pd.read_csv('heart.csv')
x= np.array(data.iloc[:, :-1])
y = np.array(data.iloc[:,-1])
print(x,y)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [45]:
data.shape

(303, 14)

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x=scaler.fit_transform(x)

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.25, random_state = 23 )

In [42]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(X_test.shape)

(227, 13)
(76, 13)
(227,)
(76, 13)


In [62]:
from tensorflow.keras import models
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

batch_size = 9
epoch = 80
model = Sequential()
model.add(Dense(units = 13, activation = 'relu'))
model.add(Dense(units = 13, activation = 'relu'))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'adam
              ',loss = 'binary_crossentropy',metrics = ['accuracy'])
model.fit(X_train,Y_train, batch_size = batch_size, epochs=epoch)
model.summary()


Epoch 1/80
26/26 [==============================] - 0s 552us/step - loss: 0.7292 - accuracy: 0.4714
Epoch 2/80
26/26 [==============================] - 0s 621us/step - loss: 0.6477 - accuracy: 0.6211
Epoch 3/80
26/26 [==============================] - 0s 588us/step - loss: 0.5868 - accuracy: 0.7004
Epoch 4/80
26/26 [==============================] - 0s 554us/step - loss: 0.5347 - accuracy: 0.7445
Epoch 5/80
26/26 [==============================] - 0s 537us/step - loss: 0.4882 - accuracy: 0.7797
Epoch 6/80
26/26 [==============================] - 0s 574us/step - loss: 0.4538 - accuracy: 0.8106
Epoch 7/80
26/26 [==============================] - 0s 576us/step - loss: 0.4253 - accuracy: 0.8238
Epoch 8/80
26/26 [==============================] - 0s 558us/step - loss: 0.4027 - accuracy: 0.8326
Epoch 9/80
26/26 [==============================] - 0s 614us/step - loss: 0.3849 - accuracy: 0.8370
Epoch 10/80
26/26 [==============================] - 0s 595us/step - loss: 0.3691 - accuracy: 0.8502

In [73]:
y_pred=model.predict(X_test)
prediction = (y_pred>0.5)*1
actual = data[['target']]

In [88]:
pred=pd.DataFrame(data=prediction, index = None, columns = ['predicted'])

In [90]:
final = pd.concat([actual,pred], axis = 1)

In [96]:
final.head()

target  predicted
0       1        0.0
1       1        1.0
2       1        1.0
3       1        1.0
4       1        0.0